# Generated by Django 4.2.27 on 2025-12-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_emergency_contact_phone_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sidecar_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
