# Generated by Django 4.2.27 on 2025-12-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_savedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
