# Generated by Django 4.2.27 on 2025-12-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_last_lat_user_last_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
