# Generated by Django 4.2.27 on 2025-12-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_address_user_date_of_birth_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barangay_residency_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='body_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='passenger_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nbi_clearance_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/'),
        ),
    ]
