# Generated by Django 4.2.27 on 2025-12-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_barangay_residency_image_user_body_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_accept_rides',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='search_radius_km',
            field=models.IntegerField(default=5),
        ),
    ]
