# Generated by Django 4.2.27 on 2025-12-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_maintenancelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='driver',
            new_name='reviewee',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='passenger',
            new_name='reviewer',
        ),
        migrations.AlterField(
            model_name='review',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.ride'),
        ),
    ]
