# Generated by Django 4.2.27 on 2026-01-13 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_fraudalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
