# Generated by Django 4.2.27 on 2026-01-15 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ride_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ride',
            name='lgu_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('payment', 'Ride Payment'), ('refund', 'Refund'), ('cashout', 'Cash Out'), ('lgu_commission', 'LGU Commission'), ('driver_earning', 'Driver Earning')], max_length=20),
        ),
        migrations.CreateModel(
            name='LGURevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purpose', models.CharField(choices=[('system_maintenance', 'System Maintenance'), ('emergency_fund', 'Emergency Fund'), ('regulatory', 'Regulatory Compliance'), ('driver_benefits', 'Driver Benefits'), ('general', 'General Fund')], default='general', max_length=50)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lgu_revenue', to='api.ride')),
            ],
            options={
                'verbose_name': 'LGU Revenue',
                'verbose_name_plural': 'LGU Revenues',
                'ordering': ['-collected_at'],
            },
        ),
    ]
