# Generated by Django 4.2.27 on 2026-01-15 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_ride_commission_rate_ride_driver_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='targeted_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_targeted_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
