# Generated by Django 4.2.27 on 2026-01-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash')], default='cash', max_length=20),
        ),
    ]
