# Generated by Django 4.2.27 on 2026-04-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
