# Generated by Django 4.2.27 on 2026-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_user_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_driver_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_queue',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('on_route', 'On The Way'), ('arrived', 'Arrived'), ('in_trip', 'In Trip'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
