# Generated by Django 4.2.27 on 2026-04-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_ride_current_driver_index_ride_driver_queue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='current_driver_index',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver_queue',
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('on_route', 'On Route'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
