# Generated by Django 4.2.27 on 2026-05-11 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_ride_current_driver_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
