# Generated by Django 4.2.27 on 2026-05-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_user_email_otp_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='start_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
