# Generated by Django 4.2.27 on 2026-05-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_scheduledride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passenger_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scheduledride',
            name='passenger_count',
            field=models.IntegerField(default=1),
        ),
    ]
