# Generated by Django 4.2.27 on 2026-07-05 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_ride_nearest_landmark_ride_notes_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_session_salt',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
