# Generated by Django 4.2.27 on 2026-07-05 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_user_jwt_session_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
