# Generated by Django 4.2.27 on 2026-07-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_ride_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='hidden_from_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='hidden_from_passenger',
            field=models.BooleanField(default=False),
        ),
    ]
