# Generated by Django 4.2.27 on 2026-07-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_ride_hidden_from_driver_ride_hidden_from_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selfie_with_license',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='tricycle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_orcr_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/'),
        ),
    ]
