# Generated by Django 4.2.27 on 2026-07-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_prune_resolved_cases_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
