web: python manage.py migrate && python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@transmart.com', 'admin123')" && daphne -b 0.0.0.0 -p $PORT trike_server.asgi:application
worker: python manage.py runworker
